version: '3.3'

services:
  rabbitmq: 
    image: rabbitmq:management
    hostname: "rabbitmq"
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    logging:
      driver: none
  cloud-mongo:
    image: mongo:latest
    hostname: "cloud-mongo"
    restart: always
    logging:
      driver: none
    ports:
      - '27017:27017'
  cloud-minio:
    image: minio/minio
    hostname: "cloud-minio"
    logging:
      driver: none
    volumes:
      - ./cloud-minio-data:/data
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: "Q3AM3UQ867SPQQA43P2F"
      MINIO_SECRET_KEY: "zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG"
    command: server /data
  model-preprocess:
    build: ./model-preprocess
    restart: always
    volumes:
      - ./model-preprocess:/app
    links:
      - rabbitmq
      - cloud-minio
    depends_on:
      - rabbitmq
      - cloud-minio
    environment:
      RABBITMQ_CONNECTION: 'rabbitmq'
      PYTHONUNBUFFERED: 1
      MINIO_ACCESS_KEY: "Q3AM3UQ867SPQQA43P2F"
      MINIO_SECRET_KEY: "zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG"
      MINIO_URL: "cloud-minio:9000"
      MINIO_BUCKET: "brains"
      MONGO_URL: "mongodb://cloud-mongo:27017"
      MONGO_DB: "logsDB"
      MONGO_COLLECTION: "preprocessor"
  model-create:
    build: ./model-create
    restart: always
    volumes:
      - ./model-create:/app
    links:
      - rabbitmq
      - cloud-minio
      - cloud-mongo
    depends_on:
      - rabbitmq
      - cloud-minio
      - cloud-mongo
    environment:
      RABBITMQ_CONNECTION: 'rabbitmq'
      PYTHONUNBUFFERED: 1
      MINIO_ACCESS_KEY: "Q3AM3UQ867SPQQA43P2F"
      MINIO_SECRET_KEY: "zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG"
      MINIO_URL: "cloud-minio:9000"
      MINIO_BUCKET: "brains"
      MONGO_URL: "mongodb://cloud-mongo:27017"
      MONGO_DB: "logsDB"
      MONGO_COLLECTION: "creator"
  model-deploy:
    build: ./model-deploy
    volumes:
      - ./model-deploy:/app
    links:
      - rabbitmq
      - cloud-minio
      - cloud-mongo
    depends_on:
      - rabbitmq
      - cloud-minio
      - cloud-mongo
    environment:
      RABBITMQ_CONNECTION: 'rabbitmq'
      PYTHONUNBUFFERED: 1
      MINIO_ACCESS_KEY: "Q3AM3UQ867SPQQA43P2F"
      MINIO_SECRET_KEY: "zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG"
      MINIO_URL: "cloud-minio:9000"
      MINIO_BUCKET: "brains"
      MONGO_URL: "mongodb://cloud-mongo:27017"
      MONGO_DB: "logsDB"
      MONGO_COLLECTION: "deployer"
      S3_ACCESS_KEY: "${S3_ACCESS_KEY}"
      S3_SECRET_KEY: "${S3_SECRET_KEY}"
      S3_BUCKET: "bti-20183"
      S3_ENDPOINT: "${S3_ENDPOINT}"
      EDGE_ENDPOINT: "http://edge-server:8000/update"
  cloud-server:
    build: ./cloud-server
    # restart: always
    hostname: "cloud-server"
    volumes:
      - ./cloud-server:/app
    ports:
      - "8000:8000"
    links:
      - rabbitmq
      - cloud-minio
      - cloud-mongo
    depends_on:
      - rabbitmq
      - cloud-minio
      - cloud-mongo
    environment:
      RABBITMQ_CONNECTION: 'rabbitmq'
      PYTHONUNBUFFERED: 1
      MINIO_ACCESS_KEY: "Q3AM3UQ867SPQQA43P2F"
      MINIO_SECRET_KEY: "zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG"
      MINIO_URL: "cloud-minio:9000"
      MINIO_BUCKET: "brains"
      MONGO_URL: "mongodb://cloud-mongo:27017"
      MONGO_DB: "logsDB"
      MONGO_COLLECTION: "cloud_server"
      PREPROCESSOR_MONGO_COLLECTION: "preprocessor"
      CREATOR_MONGO_COLLECTION: "creator"
      DEPLOYER_MONGO_COLLECTION: "deployer"
      S3_ACCESS_KEY: "${S3_ACCESS_KEY}"
      S3_SECRET_KEY: "${S3_SECRET_KEY}"
      S3_ENDPOINT: "${S3_ENDPOINT}"
      S3_BUCKET: "bti-20183"
  cloud-frontend:
    build: ./cloud-frontend
    # volumes:
    #   - ./cloud-frontend:/app
    #   - /app/node_modules
    environment:
      - HOST=0.0.0.0
    ports:
      - "3000:3000"
    links:
      - cloud-server
    depends_on:
      - cloud-server
  edge-minio:
    image: minio/minio
    hostname: "edge-minio"
    logging:
      driver: none
    volumes:
      - ./edge-minio-data:/data
    ports:
      - "9001:9000"
    environment:
      MINIO_ACCESS_KEY: "6D8D341ABA51C6ED"
      MINIO_SECRET_KEY: "HYOjcwvYuPhS6qbXS42YNkKWKfcDnV9E"
    command: server /data
  s3-minio:
    image: minio/minio
    hostname: "s3-minio"
    logging:
      driver: none
    volumes:
      - ./s3-minio-data:/data
    ports:
      - "9002:9000"
    environment:
      MINIO_ACCESS_KEY: "6D8D341ABA51C6ED"
      MINIO_SECRET_KEY: "HYOjcwvYuPhS6qbXS42YNkKWKfcDnV9E"
    command: server /data
  edge-mongo:
    image: mongo:latest
    hostname: "edge-mongo"
    restart: always
    logging:
      driver: none
    ports:
      - '27018:27017'
  edge-server:
    build: ./edge-server
    hostname: "edge-server"
    # restart: always
    volumes:
      - ./edge-server:/app
    ports:
      - "8001:8000"
    links:
      - edge-minio
      - edge-mongo
    depends_on:
      - edge-minio
      - edge-mongo
    environment:
      PYTHONUNBUFFERED: 1
      MINIO_ACCESS_KEY: "6D8D341ABA51C6ED"
      MINIO_SECRET_KEY: "HYOjcwvYuPhS6qbXS42YNkKWKfcDnV9E"
      MINIO_URL: "edge-minio:9000"
      MINIO_BUCKET: "brains"
      MONGO_URL: "mongodb://edge-mongo:27017"
      MONGO_DB: "logsDB"
      MONGO_COLLECTION: "edge_server"
      S3_ENDPOINT: "${S3_ENDPOINT}"
      # API_KEY: "KFPBCODIA6K92KZF"
  edge-put-data:
    build: ./edge-put-data
    volumes:
      - ./edge-put-data:/app
    links:
      - edge-minio
      - edge-mongo
    environment:
      PYTHONUNBUFFERED: 1
      MINIO_ACCESS_KEY: "6D8D341ABA51C6ED"
      MINIO_SECRET_KEY: "HYOjcwvYuPhS6qbXS42YNkKWKfcDnV9E"
      MINIO_URL: "edge-minio:9000"
      MINIO_BUCKET: "brains"
      MONGO_URL: "mongodb://edge-mongo:27017"
      MONGO_DB: "logsDB"
      MONGO_COLLECTION: "edge-data"
      API_KEY: "KFPBCODIA6K92KZF"