version: '3.3'

services:
  rabbitmq: 
    image: rabbitmq:management
    hostname: "rabbitmq"
    ports:
      - 5673:5672
      - 15673:15672
    logging:
      driver: none
  model-preprocess:
    build: model-preprocess/.
    restart: on-failure
    links:
      - rabbitmq
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_CONNECTION: 'rabbitmq'
      PYTHONUNBUFFERED: 1
    # command: ["./wait-for-it.sh", "rabbitmq:5672", "--", "python", "main.py"]
  model-create:
    build: ./model-create
    restart: on-failure
    links:
      - rabbitmq
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_CONNECTION: 'rabbitmq'
      PYTHONUNBUFFERED: 1
  model-deploy:
    build: ./model-deploy
    restart: on-failure
    volumes:
     - ./model-deploy:/app
    links:
      - rabbitmq
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_CONNECTION: 'rabbitmq'
      MINIO_CONNECTION: "play.min.io:9000"
      MONGO_CONNECTION: "mongodb://mongo:27017/"
      PYTHONUNBUFFERED: 1
      MINIO_ACCESS_KEY: "Q3AM3UQ867SPQQA43P2F"
      MINIO_SECRET_KEY: "zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG"
  minio:
    image: minio/minio
    hostname: "minio"
    volumes:
      - ./minio-data:/data
    ports:
      - "9001:9000"
    environment:
      MINIO_ACCESS_KEY: "Q3AM3UQ867SPQQA43P2F"
      MINIO_SECRET_KEY: "zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG"
    command: server /data
  mongo:
    image: mongo:4.0.4
    hostname: "mongo"
    ports:
    - 27017:27017