version: '3.3'

services:
  rabbitmq: 
    image: rabbitmq:management
    hostname: "rabbitmq"
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    logging:
      driver: none
  mongo:
    image: mongo:latest
    hostname: "mongo"
    restart: always
    logging:
      driver: none
    ports:
      - '27017:27017'
  cloud-minio:
    image: minio/minio
    hostname: "cloud-minio"
    volumes:
      - ./cloud-minio-data:/data
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: "Q3AM3UQ867SPQQA43P2F"
      MINIO_SECRET_KEY: "zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG"
    command: server /data
  edge-minio:
    image: minio/minio
    hostname: "edge-minio"
    volumes:
      - ./edge-minio-data:/data
    ports:
      - "9001:9000"
    environment:
      MINIO_ACCESS_KEY: "6D8D341ABA51C6ED"
      MINIO_SECRET_KEY: "HYOjcwvYuPhS6qbXS42YNkKWKfcDnV9E"
    command: server /data
  model-preprocess:
    build: ./model-preprocess
    restart: always
    volumes:
      - ./model-preprocess:/app
    links:
      - rabbitmq
      - cloud-minio
    depends_on:
      - rabbitmq
      - cloud-minio
    environment:
      RABBITMQ_CONNECTION: 'rabbitmq'
      PYTHONUNBUFFERED: 1
      MINIO_ACCESS_KEY: "Q3AM3UQ867SPQQA43P2F"
      MINIO_SECRET_KEY: "zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG"
      MINIO_URL: "cloud-minio:9000"
      MINIO_BUCKET: "brains"
      MONGO_URL: "mongodb://mongo:27017"
      MONGO_DB: "logsDB"
      MONGO_COLLECTION: "preprocessor"
  model-create:
    build: ./model-create
    volumes:
      - ./model-create:/app
    links:
      - rabbitmq
      - cloud-minio
      - mongo
    depends_on:
      - rabbitmq
      - cloud-minio
      - mongo
    environment:
      RABBITMQ_CONNECTION: 'rabbitmq'
      PYTHONUNBUFFERED: 1
      MINIO_ACCESS_KEY: "Q3AM3UQ867SPQQA43P2F"
      MINIO_SECRET_KEY: "zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG"
      MINIO_URL: "cloud-minio:9000"
      MINIO_BUCKET: "brains"
      MONGO_URL: "mongodb://mongo:27017"
      MONGO_DB: "logsDB"
      MONGO_COLLECTION: "creator"
  model-deploy:
    build: ./model-deploy
    volumes:
      - ./model-deploy:/app
    links:
      - rabbitmq
      - cloud-minio
      - mongo
    depends_on:
      - rabbitmq
      - cloud-minio
      - mongo
    environment:
      RABBITMQ_CONNECTION: 'rabbitmq'
      PYTHONUNBUFFERED: 1
      MINIO_ACCESS_KEY: "Q3AM3UQ867SPQQA43P2F"
      MINIO_SECRET_KEY: "zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG"
      MINIO_URL: "cloud-minio:9000"
      MINIO_BUCKET: "brains"
      MONGO_URL: "mongodb://mongo:27017"
      MONGO_DB: "logsDB"
      MONGO_COLLECTION: "deployer"
      S3_ACCESS_KEY: ""
      S3_SECRET_KEY: ""
      S3_BUCKET: "bti-20183"
      EDGE_ENDPOINT: "http://edge-server:8000/update"
  cloud-server:
    build: ./cloud-server
    # restart: always
    hostname: "cloud-server"
    volumes:
      - ./cloud-server:/app
    ports:
      - "8000:8000"
    links:
      - rabbitmq27018
      - cloud-minio
      - mongo
    depends_on:
      - rabbitmq
      - cloud-minio
      - mongo
    environment:
      RABBITMQ_CONNECTION: 'rabbitmq'
      PYTHONUNBUFFERED: 1
      MINIO_ACCESS_KEY: "Q3AM3UQ867SPQQA43P2F"
      MINIO_SECRET_KEY: "zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG"
      MINIO_URL: "cloud-minio:9000"
      MINIO_BUCKET: "brains"
      MONGO_URL: "mongodb://mongo:27017"
      MONGO_DB: "logsDB"
      MONGO_COLLECTION: "client"
      S3_ACCESS_KEY: ""
      S3_SECRET_KEY: ""
      S3_BUCKET: "bti-20183"
  cloud-frontend:
    build: ./cloud-frontend
    volumes:
      - ./cloud-frontend:/app
      - /app/node_modules
    environment:
      - HOST=0.0.0.0
    ports:
      - "3000:3000"
    links:
      - cloud-server
    depends_on:
      - cloud-server
  edge-server:
    build: ./edge-server
    hostname: "edge-server"
    # restart: always
    volumes:
      - ./edge-server:/app
    ports:
      - "8001:8000"
    links:
      - edge-minio
      - mongo
    depends_on:
      - edge-minio
      - mongo
    environment:
      PYTHONUNBUFFERED: 1
      MINIO_ACCESS_KEY: "Q3AM3UQ867SPQQA43P2F"
      MINIO_SECRET_KEY: "zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG"
      MINIO_URL: "cloud-minio:9000"
      MINIO_BUCKET: "brains"
      MONGO_URL: "mongodb://mongo:27017"
      MONGO_DB: "logsDB"
      MONGO_COLLECTION: "edge"